######################################################################
# Automatically generated by qmake (2.01a) Mo Aug 4 21:17:41 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
QT += xml network 
OBJECTS_DIR += obj
MOC_DIR += moc

# Input
HEADERS += src/window.h
SOURCES += src/main.cpp \
           src/window.cpp
# TRANSLATIONS += src/de.ts src/en.ts
